### ISSUE TITLE
fork to litecoin

### ISSUE THREAD

**Issue by krtschmr** [Sailias/bitcoin_payable#16]
should work if we simply fork the gem, run `sed bitcoin/litecoin` and change the api-urls for blockchain and prices.

do we need to do anything else? by theory should work, right?

**Comment by Sailias** [comment]
@krtschmr probably.  When I created this repo I wasn't even planning on open sourcing it, I was just planning on using it in a project.  That's why I didn't write it to be multi currency.

It would be more work to make it currency agnostic, but for a simple conversion to litecoin, it probably isn't much more difficult than what you outlined.

**Comment by krtschmr** [comment]
great. workin on it already: https://github.com/krtschmr/litecoin_payable
