### ISSUE TITLE
installation issue: bundle not working 

### ISSUE THREAD

**Issue by kimmiekim** [Sailias/bitcoin_payable#6]
Hi, 
 
I'm following along with you instructions and I included the gem to my Gemfile, and tried running $bundle, but I'm keep getting this error: 
``An error occurred while installing yajl-ruby (1.2.1), and Bundler cannot continue.
Make sure that `gem install yajl-ruby -v '1.2.1'` succeeds before bundling.``

I'm running this on rails 5, and ruby 2.3.0. Thanks so much!

**Comment by Sailias** [comment]
@kimmiekim that appears to be an error with installing that gem.  The latest version offered is `1.2.1` so I can't require a newer version of the gem. 

If there was a newer version available and you wanted to use that version instead of mine, you could just include that version in your Gemfile, and that will be used instead.

Please ensure you have the correct binaries installed to install that gem and try again.
